# Site settings
title:          Songhoon-log
description:    "Songhoon-log"
baseurl:        ""
url:            "https://songh-oon.github.io"

# Google Analytics
google_analytics: G-74XLGND2RG

# Author
author:
  name:         Songhoon Kim
  url:          "https://songh-oon.github.io"
  email:        songhoon1217@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
#  - jekyll-paginate-multiple
  - jekyll-seo-tag
  - jemoji 

# Permalinks
permalink:      /:year-:month-:day/:title



paginate: 5
#paginate_multiple:
#  - paginate: 4
#    paginate_path: '/study/page:num/'
#    sub_dir: '/study'
#  - paginate: 4
#    paginate_path: '/daily/page:num/'
#    sub_dir: '/daily'
#  - paginate: 4
#    paginate_path: '/thoughts/page:num/'
#    sub_dir: '/thoughts'



# Excludes
exclude: [ Gemfile, Gemfile.lock ] 

# Disqus (Set to your disqus id)
disqus: songhunyi-girog     

#timezone setting
timezone: Asia/Seoul
